---
title: "Data Visualization Part 2"
output: github_document
---

Initial Libraries
```{r}
library(tidyverse)
library(ggridges)

#Global Markdown Knitting Settings
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

Importing Data from NOAA Online Server

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

weather_df
```

# Sampe Plot as Last time

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha=0.5) +
  labs(
    title = "Temperature Plot",
    x = "Min daily temp (Degrees C)",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs Min Daily Temp in Three Locations, Data from NOAA") +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15 C")) + 
  scale_y_continuous(
    position = "right",
    trans = "sqrt", 
    #limits = c(0,30)
  )
  
```


# Adapting Colors

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha=0.5) +
  labs(
    title = "Temperature Plot",
    x = "Min daily temp (Degrees C)",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs Min Daily Temp in Three Locations, Data from NOAA") +
  viridis::scale_color_viridis(discrete = TRUE)
  #scale_color_hue(h = c(150, 300))
  
```

## Themes 

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha=0.5) +
  labs(
    title = "Temperature Plot",
    x = "Min daily temp (Degrees C)",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs Min Daily Temp in Three Locations, Data from NOAA") +
  viridis::scale_color_viridis(discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "bottom") 

```

